services:
  postgres:
    image: postgres:16
    container_name: eitautilities-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eitautilities-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: eitautilities-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - eitautilities-net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - eitautilities-net

  nginx:
    image: nginx:stable-alpine
    container_name: eitautilities-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - eitautilities-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  portainer_data:

networks:
    eitautilities-net:
      driver: bridge  
